<?php

/**
 * @file
 * Contains smmg_member.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\mollo_utils\Utility\MolloUtils;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function smmg_member_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.smmg_member':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Member Plugin for Small Messages Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function smmg_member_theme()
{
  return [
    'smmg_member' => [
      'render element' => 'children',
    ],
  ];
}


/**
 * Implements hook_form_alter().
 * @param $form
 * @param FormStateInterface $form_state
 * @param $form_id
 */
function smmg_member_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  // Member
  if (in_array($form_id, ['node_smmg_member_edit_form', 'node_smmg_member_form'])) {


// if Token field empty fill in automaticaly
    $token = MolloUtils::generateToken();
    $form['field_mollo_token']['widget'][0]['value']['#default_value'] = $token;

    // Automatic Fill Title Field
    $form['title']['#access'] = FALSE;
    $form['#entity_builders'][] = 'custom_member_node_title_builder';
  }
}

/**
 * Title builder for Member content type.
 *
 * @param $entity_type
 * @param NodeInterface $node
 * @param $form
 * @param FormStateInterface $form_state
 */
function custom_member_node_title_builder($entity_type, NodeInterface $node, $form, FormStateInterface $form_state)
{
  $module = 'Member';

  $first_name = MolloUtils::getFieldValue($node, 'first_name');
  $last_name = MolloUtils::getFieldValue($node, 'last_name');


// Build Title
  $node->setTitle($module . ' - ' . $first_name . ' ' . $last_name);
}
